### PR TITLE
Fix error cannot read property 'sessionId' of undefined

### LINKED ISSUE #192: TypeError: Cannot read property 'sessionId' of undefined
View details in Rollbar: [https://rollbar.com/mrorz/rumors-line-bot/items/220/](https://rollbar.com/mrorz/rumors-line-bot/items/220/)

```

TypeError: Cannot read property 'sessionId' of undefined
  File "/app/build/webhook/index.js", line 89, in singleUserHandler
          if (data.sessionId !== context.data.sessionId) {
  File "<anonymous>", line unknown, in runMicrotasks
  File "internal/process/task_queues.js", line 97, in processTicksAndRejections
```

### PR DESCRIPTION
**Pull request by nonumpa**
Fixes #192 

It’s because default reply `context` object doesn’t have `data` property, when the next message comes in, getting `context.data.sessionId` will have such error.

### CODE REVIEW

**Comment by MrOrz** [comment]
@nonumpa  Nice catch! Thanks for debugging. I think we can have an unit test that reproduces the case when default reply is used.

Another thing is, it seems that I cannot reproduce the bug on LINE. May I know the steps to reproduce? In this way we can verify the bug is really fixed.

**Comment by nonumpa** [comment]
Oh, the next message should be a postback, only postback messages will get `context.data.sessionId`.

**Comment by MrOrz** [comment]
> Oh, the next message should be a postback, only postback messages will get context.data.sessionId.

Thanks! So the reproduction step is clear now.

1. Send any text that shows a button (ex: `1234`)
2. Send a sticker and get "I cannot understand messages ..."
3. Click the previously shown button

I think we can have a snapshot test for the default reply (probably using sticker message as mock input) and we are good to go.

File: src/webhook/__tests__/index.js [hunk 1]
```diff
@@ -116,4 +124,56 @@ describe('Webhook router', () => {
...
+
+    /**
+     * The HTTP response isn't guaranteed the event handling to be complete
+     */
+    await sleep(500);
+
+    // snapshot reply messages
+    expect(lineClient.mock.calls).toMatchSnapshot();
+    // snapshot user context
+    expect(redis.set.mock.calls).toMatchSnapshot();
```
Comment (MrOrz) [inline src/webhook/__tests__/index.js:170]: Nit: when invoking `toMatchSnapshot` multiple times in one `it` test, we can pass in snapshot names to make snapshots easier to read.
