### PR TITLE
fix(tutorial): typing functions in tutorial

### LINKED ISSUE #357: Typing `handlers/tutorial` and removing ts-ignore in webhook index
As [discussed on Slack](https://g0v-slack-archive.g0v.ronny.tw/index/channel/C2PPMRQGP/2023-08#ts-1692067805.6942) we decided to create a new ticket for typing `handlers/tutorial` and removing ts-ignore here.

_Originally posted by @MrOrz in https://github.com/cofacts/rumors-line-bot/pull/356#discussion_r1294146538_

### PR DESCRIPTION
**Pull request by yhsiang**
To fix #357 

1. typing tutorial.js
2. typing handleInput.js
3. typing handlePostback.js

handlers/*.js should be next target

### CODE REVIEW

File: src/types/chatbotState.ts [hunk 1]
```diff
@@ -27,24 +28,29 @@ type ArgumentedEventParams = {
   input: string;
 };
 
-export type ChatbotStateHandlerParams = {
-  data: {
-    /** Used to differientiate different search sessions (searched text or media) */
-    sessionId: number;
+export declare type ChatbotEvent = (WebhookEvent | ServerChooseEvent) &
```
Comment (johnson-liang) [inline src/types/chatbotState.ts:31]: Let's remove `declare` as [discussed on slack](https://g0v-slack-archive.g0v.ronny.tw/index/channel/C2PPMRQGP/2023-08#ts-1692192126.2119)

File: src/webhook/handlers/tutorial.ts [hunk 2]
```diff
@@ -406,5 +423,5 @@ export default function tutorial(params) {
   });
   visitor.send();
 
-  return { data, event, issuedAt, userId, replies };
+  return { data, event, userId, replies, state };
```
Comment (johnson-liang) [inline src/webhook/handlers/tutorial.ts:426]: nit: actually `state` is not needed; it is also excluded from `ChatbotStateHandlerReturnType`.

Since the user can scroll back in the conversation and click buttons to jump to arbitrary previous states, it is actually not very useful to store a `state` enum in the context. That is why we excluded `state` from handler's return type, and determine what the current state is inside `singleUserHandler` with action payload instead.

Comment (yhsiang) [reply src/webhook/handlers/tutorial.ts:426]: ok then we will need this
```
let params: ChatbotStateHandlerParams | ChatbotStateHandlerReturnType = {
```

File: src/webhook/handlers/tutorial.ts [hunk 3]
```diff
@@ -190,11 +203,11 @@ function createEndingMessage() {
 }
 
 /**
- * @param {string} sessionId Search session ID
+ * @param {number} sessionId Search session ID
```
[the remark this answers is not in the document]
Comment (yhsiang) [reply src/webhook/handlers/tutorial.ts]: removed

File: src/types/chatbotState.ts (hunk 1 above)
Comment (yhsiang) [reply src/types/chatbotState.ts]: removed

**Review by johnson-liang — APPROVED** [review]
