### PR TITLE
Fix invalid replyToken, add timeout mechanism

### LINKED ISSUE #154: [LINE Client] 400: Invalid reply token.
View details in Rollbar: [https://rollbar.com/mrorz/rumors-line-bot/items/56/](https://rollbar.com/mrorz/rumors-line-bot/items/56/)

```
[LINE Client] 400: Invalid reply token.
```

### PR DESCRIPTION
**Pull request by nonumpa**
Fixes #154

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -54,9 +54,29 @@ const singleUserHandler = async (
...
   otherFields
 ) => {
+  // reply before timeout
+  // the reply token becomes invalid after a certain period of time
+  // https://developers.line.biz/en/reference/messaging-api/#send-reply-message
+  let isReplied = false;
+  setTimeout(function() {
+    if (isReplied) return;
+
+    isReplied = true;
```
Comment (MrOrz) [inline src/index.js]: We can add
```
console.log(`[LOG] Timeout ${....}`)
```

And we analyze what kind of message causes timeout next week, by look them up in logentries.

File: src/index.js [hunk 2]
```diff
@@ -54,9 +54,29 @@ const singleUserHandler = async (
...
+    lineClient('/message/reply', {
+      replyToken,
+      messages: [
+        {
+          type: 'text',
+          text: t`Line bot is busy, or we cannot handle this message. Maybe you can try again a few minutes later.`,
```
Comment (MrOrz) [inline src/index.js]: 翻譯：不好意思！系統可能在忙線中，無法及時處理您傳的訊息。請稍等幾分鐘再試試看唷。

**Comment by MrOrz** [comment]
It's working on staging! I have added a `console.log` to show when replies are aborted.
Let's push it to production and see if it resolves https://rollbar.com/mrorz/rumors-line-bot/items/56/

螢幕快照 2020-02-27 上午11 50 03
